apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: postgres
    component: storage
  name: postgres-pvc
  namespace: api-orchestrator-dev
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: fast-ssd
