[build]
builder = "NIXPACKS"
buildCommand = "cd backend && pip install -r requirements.txt && cd ../frontend && npm install && npm run build"

[deploy]
startCommand = "cd backend && python -m uvicorn src.main:app --host 0.0.0.0 --port ${PORT:-8000}"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "streamapi"
type = "web"

[services.streamapi]
port = 8000

[[databases]]
name = "streamapi-db"
plugin = "postgresql"

[[databases]]
name = "streamapi-redis"  
plugin = "redis"