apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  labels:
    app: api-orchestrator
    component: security
  name: api-orchestrator-psp
spec:
  allowPrivilegeEscalation: false
  fsGroup:
    rule: RunAsAny
  privileged: false
  requiredDropCapabilities:
  - ALL
  runAsUser:
    rule: MustRunAsNonRoot
  seLinux:
    rule: RunAsAny
  volumes:
  - configMap
  - emptyDir
  - projected
  - secret
  - downwardAPI
  - persistentVolumeClaim
